import java.security.KeyPair;
import javax.swing.JOptionPane; // para los mensajes de dialogo (cuando marque error)
/**
 *
 * @author Dany
 */
public class INTERFAZ extends javax.swing.JFrame {

    /**
     * Creates new form INTERFAZ
     */
    public INTERFAZ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblmensaje = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        txtmensaje = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblencritado = new javax.swing.JLabel();
        lbldesencriptado = new javax.swing.JLabel();
        lblfirma = new javax.swing.JLabel();
        txtencriptado = new javax.swing.JTextField();
        txtdesencriptado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareafirma = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        btnsalir = new javax.swing.JButton();
        btnencriptarfirmar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblmensaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblmensaje.setText("Mensaje a encriptar y firmar:");

        lbltitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitulo.setText("CIFRADO Y FIRMAS DIGITALES - DANY HERNANDEZ");

        txtmensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtmensaje.setName(""); // NOI18N

        lblencritado.setText("Texto encriptado:");

        lbldesencriptado.setText("Texto encriptado:");

        lblfirma.setText("Mensaje firmado:");

        txtencriptado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtencriptado.setEnabled(false);

        txtdesencriptado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtdesencriptado.setEnabled(false);

        txtareafirma.setColumns(20);
        txtareafirma.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txtareafirma.setRows(5);
        txtareafirma.setEnabled(false);
        jScrollPane1.setViewportView(txtareafirma);

        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnencriptarfirmar.setText("ENCRIPTAR Y FIRMAR");
        btnencriptarfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnencriptarfirmarActionPerformed(evt);
            }
        });

        btnnuevo.setText("NUEVO CIFRADO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(txtmensaje)
                    .addComponent(txtencriptado)
                    .addComponent(txtdesencriptado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsalir))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmensaje)
                            .addComponent(lbldesencriptado)
                            .addComponent(lblfirma)
                            .addComponent(btnencriptarfirmar)
                            .addComponent(lblencritado))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnencriptarfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblencritado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtencriptado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldesencriptado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdesencriptado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblfirma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalir)
                    .addComponent(btnnuevo))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        lblmensaje.getAccessibleContext().setAccessibleName("lblmensaje");
        lbltitulo.getAccessibleContext().setAccessibleName("lbltituloventana");
        txtmensaje.getAccessibleContext().setAccessibleName("txtmensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnencriptarfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnencriptarfirmarActionPerformed

        String mensaje = txtmensaje.getText(); // el valor del cuadro de texto lo asignamos a variable
        if(mensaje.equals("")) { // si la variable esta vacia
            // mandamos mensaje de error
            JOptionPane.showMessageDialog(null, "DEBE INGRESAR UN MENSAJE", "CAMPO DE MENSAJE VACIO", JOptionPane.ERROR_MESSAGE);
            txtmensaje.setText(""); // limpiamos el cuadro de texto
        }else{
            try {
                txtmensaje.enable(false);
                // INSTANCIAMOS LA CLASE QUE GENERA LAS LLAVES, ENCRIPTA Y DESENCRIPTA Y LA FIRMA DIGITAL
                LLAVES llaves = new LLAVES();
                // GENERAMOS LAS LLAVES: PUBLICA Y PROVADA
                KeyPair parllaves = llaves.generarLlaves();
                // ENCRIPTAMOS EL MENSAJE Y LO MOSTRAMOS EN CAJA DE TEXTO
                String textocifrado = llaves.encriptar(mensaje, parllaves.getPublic());
                // DESENCRIPTAMOS EL MENSAJE Y LO MOSTRAMOS
                String textodescifrado = llaves.desencriptar(textocifrado, parllaves.getPrivate());
                // FIRMA DIGITAL DEL MENSAJE
                String firma = llaves.firma(mensaje, parllaves.getPrivate());
                // VALIDAMOS LA FIRMA
                boolean esvalida = llaves.verificar(mensaje, firma, parllaves.getPublic());
                // DEPENDE DEL RESULTADO (TRUE FALSE) MOSTRAREMOS LOS RESULTADOS EN LOS CAMPOS
                // O MANDAMOS MENSAJE DE ERROR
                String respuesta = Boolean.toString(esvalida); // el resultado lo asignamos a variable
                if(respuesta.equals("true")){ // si es true (firma valida
                    txtareafirma.setLineWrap(true); // para que al llegar al final del control, se siga en la siguiente linea
                    txtencriptado.setText(textocifrado); // mostramos el texto encriptado
                    txtdesencriptado.setText(textodescifrado); // mostramos el texto desencriptado con el metodo
                    txtareafirma.setText(firma); // mostramos la firma
                    // y en un mensaje mostramos la validez de la firma
                    JOptionPane.showMessageDialog(null, "MENSAJE CIFRADO Y FIRMADO", "RESPUESTA", JOptionPane.INFORMATION_MESSAGE);
                }
              } catch (Exception ex) {
                // si la generacion de las llaves, encriptado y firma falla, lanzo excepcion y muestro
                // mensaje de error
                txtmensaje.setText("NO SE PUDO ENCRIPTAR / FIRMAR EL MENSAJE /n" + ex);
                // limpio nuevamente los elementos de la ventana para nueva captura
                txtencriptado.setText("");
                txtdesencriptado.setText("");
                txtareafirma.setText("");  
            }   
        }
    }//GEN-LAST:event_btnencriptarfirmarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0); // salir del sistema
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        txtmensaje.enable(true); // habilitamos el cuadro de texto del mensaje
        // limpiamos los elementos para que sean llenados nuevamente
        txtmensaje.setText("");
        txtencriptado.setText("");
        txtdesencriptado.setText("");
        txtareafirma.setText("");
    }//GEN-LAST:event_btnnuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new INTERFAZ().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnencriptarfirmar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbldesencriptado;
    private javax.swing.JLabel lblencritado;
    private javax.swing.JLabel lblfirma;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextArea txtareafirma;
    private javax.swing.JTextField txtdesencriptado;
    private javax.swing.JTextField txtencriptado;
    private javax.swing.JTextField txtmensaje;
    // End of variables declaration//GEN-END:variables
}
